---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'docker-registry.gso.harwell.me/scottharwell/ansible-runner-with-certs:ee-supported-rhel8-2.0.1-11'

ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
#   system: bindep.txt

# additional_build_steps:
#   prepend: |
#     RUN whoami
#     RUN cat /etc/os-release
#   append:
#     - RUN echo This is a post-install command!
